<?php

class TicketAndGo extends Empresa
{
    /**
     * @param Funcionario $funcionario
     * @return void
     * Métoto responsável por adicionar funcionário através de alguns tipos (HONESTO, COOPERATIVO, ESPERTO, MOTIVADO)
     */
    public function addFuncionario(Funcionario $funcionario)
    {
        if($funcionario->tipo == K_FUNCIONARIO_HONESTO || $funcionario->tipo == K_FUNCIONARIO_COOPERATIVO
            || $funcionario->tipo == K_FUNCIONARIO_ESPERTO || $funcionario->tipo == K_FUNCIONARIO_MOTIVADO){
            parent::addFuncionario($funcionario); // TODO: Change the autogenerated stub
        }
    }
}